/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Alloy:": "合金：",
    "City Funds:": "城市资金：",
    "day/night": "日/夜",
    "Elec:": "电：",
    "Fire station": "消防站",
    "Grocery:": "杂货店：",
    "guide": "指南",
    "input needed:": "需要输入：",
    "Lumber:": "木材：",
    "load": "加载",
    "Metal works": "金属加工",
    "Metal:": "金属：",
    "Oil:": "石油：",
    "Plastic:": "塑料：",
    "save": "保存",
    "title": "首页",
    "Water:": "水：",
    "Water pump and tower": "水泵和塔",
    "Alloy refinery": "合金精炼厂",
    "Electronic Works": "电子加工",
    "Grocery store": "杂货店",
    "Hospital": "医院",
    "materials needed:": "需要材料：",
    "Plastic Works": "塑料加工",
    "Police station": "警局",
    "Road intersection": "道路交叉口",
    "Road left": "左侧道路",
    "Road right": "右侧道路",
    "Wood works": "木头加工",
    "High rise commercial": "商业高层",
    "Oil refinery": "炼油厂",
    "alloy:": "合金：",
    "Building must be next to a road": "建筑物必须紧挨着马路",
    "electric:": "供电：",
    "grocery:": "杂货店：",
    "metal:": "金属：",
    "oil:": "石油：",
    "plastic:": "塑料：",
    "wood:": "木头：",
    "Production stats:   water:": "生产统计：水：",
    "Not enough electronics": "没有足够的电力",
    "Not enough lumber": "没有足够的木材",
    "Not enough metals": "没有足够的金属",
    "Not enough alloys": "没有足够的合金",
    "Not enough gallonsOfOil": "没有足够的 加仑油",
    "Can not place road on spot already taken or on water. to remove a building click on spot and use action button.": "不能在已经占用的地方或在水面上放置道路。 要移除建筑物，请点击地块并使用操作按钮。",
    "game saved": "游戏已保存",
    "game loaded": "游戏已加载",
    "\n\t\t\t\n\t\t\tBecause of that you don't need to concentrate on those buildins at first,": "\n\t\t\t\n\t\t\t因为你一开始不需要专注于那些构建，",
    "(sickness causes the people to move out and house sold, same effect as if destroyed by fire)": "（疾病导致人搬家卖房，效果与被火烧毁一样）",
    "Afterward start building residential small houses.": "之后开始建造住宅小房子。",
    "Build up your city by selecting roads and buildings from the menu and placing them on the map.": "通过从菜单中选择道路和建筑物并将它们放置在地图上来建立您的城市。",
    "Disaster Log": "灾难日志",
    "Either a robbery, a fire, or sickness.": "要么是抢劫，要么是火灾，要么是疾病。",
    "fires by the Fire Station, and sickness by the Hospital.": "火灾由消防局负责，生病由医院负责。",
    "first get alloy factories, then plastic and electric so you can make a fire station.": "首先获得合金工厂，然后是塑料和电力工厂，这样你就可以建造一个消防站。",
    "Gameplay video": "游戏视频",
    "Idle City Sim 2051 Guide": "放置城市模拟 2051 指南",
    "If mishaps are on, every so often a disaster will happen.": "如果发生意外，每隔一段时间就会发生灾难。",
    "If there is 1 Fire Station per 80 buildings and roads, fires always get put out.": "如果每 80 座建筑物和道路有 1 个消防站，火灾总会被扑灭。",
    "If there is 1 Hospital per 75 buildings and roads, sickness always gets cured.": "如果每 75 座建筑物和道路有 1 家医院，那么疾病总会得到治愈。",
    "If there is 1 Police station per 120 buildings, including roads, robberies always get caught.": "如果每 120 座建筑物（包括道路）有 1 个警察局，抢劫总会被抓获。",
    "If you run low on city funds you can click on the alloy amount to turn 10 alloy into 100 cityFunds:": "如果您的城市资金不足，您可以点击合金数量将 10 合金变成 100 城市资金：",
    "More Games": "更多游戏",
    "privacy policy": "隐私政策",
    "Robberies are stopped by Police,": "抢劫被警察制止，",
    "Sickness only happens in residential buildings.": "疾病只发生在居民楼里。",
    "tad's basic game objects": "tad 的基本游戏对象",
    "Then build up to police.": "然后建立警察。",
    "There are four regions that can be built up.": "可以建立四个区域。",
    "This game was made using": "这个游戏是用",
    "to dig for water, wood, metal and oil.": "挖掘水、木材、金属和石油。",
    "You can click on Metal to refine 2 Alloy from 1 Metal.": "您可以点击金属从 1 金属精炼 2 合金。",
    "You can click/touch the shovel in the lower right corner when on a empty spot in the map": "在地图上的空白处，您可以点击/触摸右下角的铲子",
    "You can hover over each emergency building to see how many buildings there are;": "您可以将鼠标悬停在每个紧急建筑物上，以查看有多少建筑物；",
    "You can turn off mishaps in the options menu from the title screen.": "您可以在标题屏幕的选项菜单中关闭不幸事件。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "A": "A",
    "G": "G",
    "B": "B",
    "E": "E",
    "O": "O",
    "S": "S",
    "T": "T",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "High rise commercial type ": "高层商务类型 ",
    "House type ": "房屋类型 ",
    "number of fire: ": "火灾数量：",
    "total structures: ": "总计建筑：",
    "number of hospital: ": "医院数量：",
    "number of police: ": "警局数量：",
    "High rise residential type ": "高层住宅类型 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " You can use the shovel to dig for basic minerals": "， 您可以使用铲子挖掘基础矿物",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) metals$/, '$1 金属'],
    [/^([\d\.,]+) lumber$/, '$1 木材'],
    [/^([\d\.,]+) gallonsOfWater$/, '$1 加仑水'],
    [/^([\d\.,]+) bagsOfGroceries$/, '$1 杂货袋'],
    [/^([\d\.,]+) alloys$/, '$1 合金'],
    [/^([\d\.,]+) plastics$/, '$1 塑料'],
    [/^([\d\.,]+) gallonsOfOil$/, '$1 加仑油'],
    [/^([\d\.,]+) electronics$/, '$1 电力'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^outputs: (.+) metals$/, '输出：$1 金属'],
    [/^outputs: (.+) plastics$/, '输出：$1 塑料'],
    [/^outputs: (.+) bagsOfGroceries$/, '输出：$1 杂货袋'],
    [/^outputs: (.+) gallonsOfOil$/, '输出：$1 加仑油'],
    [/^outputs: (.+) electronics$/, '输出：$1 电力'],
    [/^outputs: (.+) alloys$/, '输出：$1 合金'],
    [/^outputs: (.+) lumber$/, '输出：$1 木材'],
    [/^outputs: (.+)$/, '输出：$1'],
    [/^materials needed: (.+) metals$/, '需要材料：$1 金属'],
    [/^materials needed: (.+) electronics$/, '需要材料：$1 电力'],
    [/^materials needed: (.+) alloys$/, '需要材料：$1 合金'],
    [/^materials needed: (.+) plastics$/, '需要材料：$1 塑料'],
    [/^materials needed: (.+) lumber$/, '需要材料：$1 木材'],
    [/^input needed: (.+) bagsOfGroceries$/, '需要输入：$1 杂货袋'],
    [/^input needed: (.+) alloys$/, '需要输入：$1 合金'],
    [/^input needed: (.+) metals$/, '需要输入：$1 金属'],
    [/^input needed: (.+) lumber$/, '需要输入：$1 木材'],
    [/^input needed: (.+) gallonsOfOil$/, '需要输入：$1 加仑油'],
    [/^input needed: (.+) gallonsOfWater$/, '需要输入：$1 加仑水'],
    [/^outputs: (.+) gallonsOfWater$/, '输出：$1 加仑水'],
    [/^outputs: (.+) cityFunds$/, '输出：$1 城市资金'],
    [/^cost: (.+) City Funds$/, '成本：$1 城市资金'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);